### PR TITLE
Contribution - Added Fullbright mod

### PR DESCRIPTION
**Pull request by Hot-Tutorials**
Needs to be edited so it can save the value...

### CODE REVIEW

**Comment by DanterusDev** [comment]
Can you pull from the current main Sorus repo then add the fullbright again, there are a lot of conflicts with stuff so it would be appreciated.

**Comment by Hot-Tutorials** [comment]
> Can you pull from the current main Sorus repo then add the fullbright again, there are a lot of conflicts with stuff so it would be appreciated.

Sure I'll do it on saturday if you don't mind!

**Comment by DanterusDev** [comment]
test

**Comment by DanterusDev** [comment]
discord webhook working I think

**Pull request closed without merging**
